server:
  port: 8080
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    tasks:
      jdbc-url: jdbc:postgresql://localhost:5432/eisetasks
      username: fokina
      password: password
      driver-class-name: org.postgresql.Driver
  profiles:
    active: console-and-file-logging

jwt:
  issuer: 'tatianamezzanine@gmail.com'
  signingKey: 'ahojabeceda911cz1e7r7'
  aTokenDuration: 30
logging:
    path: logs
    file: logs.log

default:
  status: inbox
  order: desc
  page: 1
  size: 25
  min-size: 10
  max-size: 50
  min-page: 1
query:
  status: status
  order: order
  page: page
  size: size
  main-path: /tasks
app:
  name: 'hw-spring-security'